events {
  worker_connections 4096;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;

    gzip on;
    gzip_types application/javascript application/json text/css;

    root /app;
    index index.html;

    location / {
      try_files $uri $uri/ $uri.html /index.html;
    }

    location = /healthy {
      proxy_pass http://games-api/ready;
    }

    location = /ready {
      proxy_pass http://games-api/ready;
    }
  }
}