services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 12345
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 10s

  redis:
    image: redis/redis-stack:7.2.0-v6-arm64
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - redis

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      redis:


volumes:
  pgdata:
  redis:
  rabbitmq-data:


networks:
  redis:
