name: sigma-preview
services:
  control-api:
    build:
      context: ../
      dockerfile: Dockerfile
      target: control-api
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env.development
  
  control-app:
    build:
      context: ../
      dockerfile: Dockerfile
      target: control-app
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env.development

  games-bot:
    build:
      context: ../
      dockerfile: Dockerfile
      target: games-bot
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env.development