events {
  worker_connections 4096;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  map $cookie_cf_authorization $set_cf_auth_cookie {
    '' '';
    default 'CF_Authorization=$cookie_cf_authorization;domain=.sigmacloud.app;path=/;httponly;secure;samesite=none;max-age=600';
  }

  server {
    listen 80;

    gzip on;
    gzip_types application/javascript application/json text/css;

    root /app;
    index index.html;

    location / {
      try_files $uri $uri/ $uri.html /index.html;
      add_header Set-Cookie $set_cf_auth_cookie;
    }

    location /health {
      access_log off;
      add_header Content-Type text/plain;
      return 200 "Healthy";
    }
  }
}