events {
  worker_connections  4096;
}

http {
  server {
    listen 80;

    gzip on;
    gzip_types application/javascript application/json text/css;

    root /app;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
  }
}