managers:
  hosts:
    control:
      ansible_user: root
      ansible_host: 188.119.112.142
    monitoring:
      ansible_user: root
      ansible_host: 188.119.113.85

workers:
  hosts:
    worker1:
      ansible_user: root
      ansible_host: 188.119.112.223