ALTER TABLE "Session" RENAME COLUMN "id" TO "oldId";
ALTER TABLE "Session" DROP CONSTRAINT "Session_pkey";
ALTER TABLE "Session" ALTER COLUMN "oldId" DROP NOT NULL;
ALTER TABLE "Session" ADD COLUMN "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL;
ALTER TABLE "Session" DROP COLUMN IF EXISTS "oldId";
