ALTER TABLE "ChatMessage" RENAME COLUMN id TO old_id;
ALTER TABLE "ChatMessage" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "ChatMessage_id_seq";
ALTER TABLE "ChatMessage" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY (sequence name "ChatMessage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);
UPDATE "ChatMessage" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "ChatMessage";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "ChatMessage_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "ChatMessage" ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE "ChatMessage" DROP COLUMN old_id;
ALTER TABLE "ChatMessage" ADD PRIMARY KEY (id);
