ALTER TABLE "Deposit" RENAME COLUMN id TO old_id;
ALTER TABLE "Deposit" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "Deposit_id_seq";
ALTER TABLE "Deposit" ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Deposit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
UPDATE "Deposit" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "Deposit";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "Deposit_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "Deposit" ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE "Deposit" DROP COLUMN old_id;
ALTER TABLE "Deposit" ADD PRIMARY KEY (id);
