ALTER TABLE "GameRecord" RENAME COLUMN id TO old_id;
ALTER TABLE "GameRecord" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "GameRecord_id_seq";
ALTER TABLE "GameRecord" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY (sequence name "GameRecord_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);
UPDATE "GameRecord" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "GameRecord";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "GameRecord_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "GameRecord" ALTER COLUMN id SET GENERATED ALWAYS;

ALTER TABLE "Balance" DROP CONSTRAINT "Balance_maxWinGameId_GameRecord_id_fk";
ALTER TABLE "Balance" DROP CONSTRAINT "Balance_maxMultiplierGameId_GameRecord_id_fk";

ALTER TABLE "GameRecord" DROP COLUMN old_id;

ALTER TABLE "GameRecord" ADD PRIMARY KEY (id);
ALTER TABLE "Balance" ADD CONSTRAINT "Balance_maxWinGameId_GameRecord_id_fk" FOREIGN KEY ("maxWinGameId") REFERENCES "public"."GameRecord"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "Balance" ADD CONSTRAINT "Balance_maxMultiplierGameId_GameRecord_id_fk" FOREIGN KEY ("maxMultiplierGameId") REFERENCES "public"."GameRecord"("id") ON DELETE cascade ON UPDATE no action;

