ALTER TABLE "Profile" RENAME COLUMN id TO old_id;
ALTER TABLE "Profile" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "Profile_id_seq";
ALTER TABLE "Profile" ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
UPDATE "Profile" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "Profile";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "Profile_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "Profile" ALTER COLUMN id SET GENERATED ALWAYS;

ALTER TABLE "ChatMessage" DROP CONSTRAINT "ChatMessage_profileId_Profile_id_fk";

ALTER TABLE "Profile" DROP COLUMN old_id;

ALTER TABLE "Profile" ADD PRIMARY KEY (id);
ALTER TABLE "ChatMessage" ADD CONSTRAINT "ChatMessage_profileId_Profile_id_fk" FOREIGN KEY ("profileId") REFERENCES "public"."Profile"("id") ON DELETE cascade ON UPDATE no action;
