ALTER TABLE "ReferralCampaign" RENAME COLUMN id TO old_id;
ALTER TABLE "ReferralCampaign" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "ReferralCampaign_id_seq";
ALTER TABLE "ReferralCampaign" ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ReferralCampaign_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
UPDATE "ReferralCampaign" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "ReferralCampaign";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "ReferralCampaign_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "ReferralCampaign" ALTER COLUMN id SET GENERATED ALWAYS;

ALTER TABLE "ReferrerTransaction" DROP CONSTRAINT "ReferrerTransaction_referralCampaignId_ReferralCampaign_id_fk";
ALTER TABLE "Session" DROP CONSTRAINT "Session_referralCampaignId_ReferralCampaign_id_fk";

ALTER TABLE "ReferralCampaign" DROP COLUMN old_id;

ALTER TABLE "ReferralCampaign" ADD PRIMARY KEY (id);
ALTER TABLE "ReferrerTransaction" ADD CONSTRAINT "ReferrerTransaction_referralCampaignId_ReferralCampaign_id_fk" FOREIGN KEY ("referralCampaignId") REFERENCES "public"."ReferralCampaign"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "Session" ADD CONSTRAINT "Session_referralCampaignId_ReferralCampaign_id_fk" FOREIGN KEY ("referralCampaignId") REFERENCES "public"."ReferralCampaign"("id") ON DELETE set null ON UPDATE no action;
