ALTER TABLE "ReferrerTransaction" RENAME COLUMN id TO old_id;
ALTER TABLE "ReferrerTransaction" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "ReferrerTransaction_id_seq";
ALTER TABLE "ReferrerTransaction" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY (sequence name "ReferrerTransaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);
UPDATE "ReferrerTransaction" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "ReferrerTransaction";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "ReferrerTransaction_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "ReferrerTransaction" ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE "ReferrerTransaction" DROP COLUMN old_id;
ALTER TABLE "ReferrerTransaction" ADD PRIMARY KEY (id);
