ALTER TABLE "ReferrerWithdrawal" RENAME COLUMN id TO old_id;
ALTER TABLE "ReferrerWithdrawal" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "ReferrerWithdrawal_id_seq";
ALTER TABLE "ReferrerWithdrawal" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY (sequence name "ReferrerWithdrawal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);
UPDATE "ReferrerWithdrawal" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "ReferrerWithdrawal";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "ReferrerWithdrawal_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "ReferrerWithdrawal" ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE "ReferrerWithdrawal" DROP COLUMN old_id;
ALTER TABLE "ReferrerWithdrawal" ADD PRIMARY KEY (id);
