ALTER TABLE "Transaction" RENAME COLUMN id TO old_id;
ALTER TABLE "Transaction" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "Transaction_idn_seq";
ALTER TABLE "Transaction" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY (sequence name "Transaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);
UPDATE "Transaction" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "Transaction";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "Transaction_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "Transaction" ALTER COLUMN id SET GENERATED ALWAYS;

ALTER TABLE "GameRecord" DROP CONSTRAINT "GameRecord_transaction_id_fkey";
ALTER TABLE "Deposit" DROP CONSTRAINT "Deposit_transactionId_Transaction_id_fk";
ALTER TABLE "Withdrawal" DROP CONSTRAINT "Withdrawal_transactionId_Transaction_id_fk";

ALTER TABLE "Transaction" DROP COLUMN old_id;

ALTER TABLE "Transaction" ADD PRIMARY KEY (id);
ALTER TABLE "GameRecord" ADD CONSTRAINT "GameRecord_transaction_id_fkey" FOREIGN KEY ("transactionId") REFERENCES "Transaction" (id);
ALTER TABLE "Deposit" ADD CONSTRAINT "Deposit_transactionId_Transaction_id_fk" FOREIGN KEY ("transactionId") REFERENCES "public"."Transaction"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "Withdrawal" ADD CONSTRAINT "Withdrawal_transactionId_Transaction_id_fk" FOREIGN KEY ("transactionId") REFERENCES "public"."Transaction"("id") ON DELETE cascade ON UPDATE no action;
