ALTER TABLE "Withdrawal" RENAME COLUMN id TO old_id;
ALTER TABLE "Withdrawal" ALTER COLUMN old_id DROP DEFAULT;
DROP SEQUENCE "Withdrawal_id_seq";
ALTER TABLE "Withdrawal" ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Withdrawal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
UPDATE "Withdrawal" SET id = old_id;

DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(old_id), 0) INTO max_id FROM "Withdrawal";
    
    IF max_id > 0 THEN
        EXECUTE format('ALTER SEQUENCE "Withdrawal_id_seq" RESTART WITH %s', max_id + 1);
    END IF;
END $$;

ALTER TABLE "Withdrawal" ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE "Withdrawal" DROP COLUMN old_id;
ALTER TABLE "Withdrawal" ADD PRIMARY KEY (id);
