tls:
  certificates:
    - certFile: /ssl/local.crt
      keyFile: /ssl/local.key

entryPoints:
  web:
    address: ":443"
    http:
      tls: {}

http:
  routers:
    auth-app:
      rule: "Host(`auth.local`)"
      entryPoints:
        - web
      service: auth-app
      tls: {}

  services:
    auth-app:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4321"