name: sigma

services:
  postgres:
    image: ghcr.io/fboulnois/pg_uuidv7:1.6.0
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres.init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_PASSWORD: SECRET_REMOVED

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - 6379:6379
    volumes:
      - dragonflydata:/data
    environment:
      REDIS_ARGS: --requirepass SECRET_REMOVED

  auth-proxy:
    image: traefik:v3.2
    command:
      - "--entrypoints.web.address=:443"
      - "--providers.file.directory=/etc/traefik/config"
      - "--providers.file.watch=true"
    ports:
      - "443:443"
    volumes:
      - "../ssl:/ssl"
      - "./auth-proxy.traefik.yaml:/etc/traefik/config/auth-proxy.traefik.yaml"

volumes:
  pgdata:
  dragonflydata:
  rabbitmq-data:
