---
- name: Setup SSH
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Copy SSH key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '../../ssh/id_rsa.pub') }}"

    - name: Remove redundant password authentication lines
      replace:
        path: '/etc/ssh/sshd_config'
        after: 'PasswordAuthentication'
        regexp: '^(.*)PasswordAuthentication(.*)$'
        replace: ''

    - name: Disable password authentication
      lineinfile:
        path: '/etc/ssh/sshd_config'
        regexp: '^(.*)PasswordAuthentication(.*)$'
        line: 'PasswordAuthentication no'

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

- name: Setup dependencies
  hosts: all
  become: true
  vars:
    arch_mapping:
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service

- name: Setup Docker swarm
  hosts: control
  become: true

  tasks:
    - name: Initialize swarm
      shell: docker swarm init --advertise-addr {{ hostvars.control.ansible_default_ipv4.address }}
      ignore_errors: true

    - name: Get swarm manager join token
      shell: docker swarm join-token -q manager
      register: manager_token

    - name: Get swarm worker join token
      shell: docker swarm join-token -q worker
      register: worker_token

- name: Join managers to swarm
  hosts: managers:!control
  become: true

  tasks:
    - name: Join swarm
      shell: docker swarm join --token {{ hostvars.control.manager_token.stdout }} {{ hostvars.control.ansible_default_ipv4.address }}:2377
      ignore_errors: true

- name: Join workers to swarm
  hosts: workers
  become: true

  tasks:
    - name: Join swarm
      shell: docker swarm join --token {{ hostvars.control.worker_token.stdout }} {{ hostvars.control.ansible_default_ipv4.address }}:2377
      ignore_errors: true
