name: Build development images with Google Cloud Build

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      games-db-migration:
        type: boolean
        default: false

env:
  DOCKER_REGISTRY: europe-west4-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker

concurrency:
  group: ${{ github.workflow }}

jobs:
  timestamp:
    name: Get current unix timestamp
    runs-on: [ubuntu-22.04]

    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}

    steps:
      - name: Get current unix timestamp
        id: timestamp
        uses: release-kit/unix-timestamp@v1

  affected:
    name: Get affected apps
    runs-on: [ubuntu-22.04]

    outputs:
      apps: ${{ steps.affected.outputs.affected_apps }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        id: pnpm
        with:
          version: 9.15.2
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Run checks for affected packages
        run: pnpm check:affected

      - name: Output affected apps
        id: affected
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            apps=()

            if [ "${{ github.event.inputs.games-db-migration }}" == "true" ]; then
              apps+=("@migrations/games-db-migration")
            fi

            echo "affected_apps=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -s -c .)" >> $GITHUB_OUTPUT
          else
            echo "affected_apps=$(pnpm nx show projects --type=app --affected --json)" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build
    needs: [affected, timestamp]
    runs-on: [ubuntu-22.04]

    if: needs.affected.outputs.apps != '[]'

    strategy:
      fail-fast: false
      matrix:
        packageName: ${{ fromJson(needs.affected.outputs.apps) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse package name
        id: parse
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.packageName }}
          pattern: '^@?(?<scope>.*)\/(?<name>.*)$'

      - name: Check if hash check should be used
        id: hash-check
        run: |
          if [[ "${{ steps.parse.outputs.scope }}" =~ ^(apps|apis|bots)$ ]]; then
            echo "should_check=true" >> $GITHUB_OUTPUT
          else
            echo "should_check=false" >> $GITHUB_OUTPUT
          fi

      - uses: pnpm/action-setup@v4
        if: steps.hash-check.outputs.should_check == 'true'
        id: pnpm
        with:
          version: 9.15.2
          run_install: false

      - name: Install Node.js
        if: steps.hash-check.outputs.should_check == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: oven-sh/setup-bun@v2
        if: steps.hash-check.outputs.should_check == 'true'
        with:
          bun-version: 1.1.42

      - name: Install dependencies
        if: steps.hash-check.outputs.should_check == 'true'
        run: pnpm install --frozen-lockfile

      - name: Build package
        if: steps.hash-check.outputs.should_check == 'true'
        run: pnpm nx run ${{ matrix.packageName }}:build

      - name: Calculate hash for dist and additional files
        id: calculate-hash
        if: steps.hash-check.outputs.should_check == 'true'
        run: |
          echo "hash=${{ hashFiles(format('apps/{0}/dist/**', steps.parse.outputs.name), format('apps/{0}/scripts/**', steps.parse.outputs.name), format('apps/{0}/nginx.conf', steps.parse.outputs.name)) }}" >> $GITHUB_OUTPUT

      - name: Gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          skip_install: true

      - name: Build on Google Cloud
        run: |
          image=${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}

          cat <<EOF > cloudbuild.yaml
          steps:
            - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
              id: 'check-cache'
              entrypoint: 'sh'
              args:
                - '-c'
                - |
                  if [ "${{ steps.hash-check.outputs.should_check }}" = "true" ]; then
                    echo "Checking cache for hash: ${{ steps.calculate-hash.outputs.hash }}"
                    if gsutil -q stat gs://sigma-games_cloudbuild_cache/build-hash/${{ steps.calculate-hash.outputs.hash }}; then
                      echo "Cache hit for ${{ steps.calculate-hash.outputs.hash }}. Exiting build."
                      exit 0
                    else
                      echo "Cache miss for ${{ steps.calculate-hash.outputs.hash }}. Proceeding with build."
                    fi
                  else
                    echo "Hash check disabled for this image. Proceeding with build."
                  fi

            - name: "gcr.io/cloud-builders/docker"
              id: "build"
              waitFor: ['check-cache']
              env:
                - "DOCKER_BUILDKIT=1"
              args:
                - build
                - --target=${{ steps.parse.outputs.name }}
                - --tag=$image:latest
                - --tag=$image:dev-${{ needs.timestamp.outputs.timestamp }}
                - --build-arg=sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}
                - --build-arg=sentry_release=dev-${{ needs.timestamp.outputs.timestamp }}
                - .

            - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
              id: 'save-cache'
              waitFor: ['build']
              entrypoint: 'sh'
              args:
                - '-c'
                - |
                  if [ "${{ steps.hash-check.outputs.should_check }}" = "true" ]; then
                    echo "Saving hash ${{ steps.calculate-hash.outputs.hash }} to GCS"
                    echo "Build completed successfully" | gsutil cp - gs://sigma-games_cloudbuild_cache/build-hash/${{ steps.calculate-hash.outputs.hash }}
                  else
                    echo "Hash saving skipped as hash check is disabled."
                  fi

          images:
            - $image:latest
            - $image:dev-${{ needs.timestamp.outputs.timestamp }}
          EOF

          gcloud builds submit . \
            --config cloudbuild.yaml \
            --region europe-west1 \
            --async
