name: Build development images with Google Cloud Build

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      games-db-migration:
        type: boolean
        default: false

env:
  DOCKER_REGISTRY: ${{ vars.GCLOUD_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker

concurrency:
  group: ${{ github.workflow }}

jobs:
  timestamp:
    name: Get current unix timestamp
    runs-on: [ubuntu-22.04]

    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}

    steps:
      - name: Get current unix timestamp
        id: timestamp
        uses: release-kit/unix-timestamp@v1

  affected:
    name: Get affected apps
    runs-on: [ubuntu-22.04]

    outputs:
      apps: ${{ steps.affected.outputs.apps }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        id: pnpm
        with:
          version: 9.15.2
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Run checks for affected packages
        run: pnpm check:affected

      - name: Output affected apps
        id: affected
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            apps=()

            if [ "${{ github.event.inputs.games-db-migration }}" == "true" ]; then
              apps+=("@migrations/games-db-migration")
            fi

            echo "apps=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -s -c .)" >> $GITHUB_OUTPUT
          else
            echo "apps=$(pnpm nx show projects --type=app --affected --json)" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build
    needs: [affected, timestamp]
    runs-on: [ubuntu-22.04]

    if: needs.affected.outputs.apps != '[]'

    strategy:
      fail-fast: false
      matrix:
        packageName: ${{ fromJson(needs.affected.outputs.apps) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        id: pnpm
        with:
          version: 9.15.2
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42

      - name: Define scopes for hash check
        id: hash-check-scopes
        run: echo "::set-output name=scopes::apps,apis"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm nx run ${{ matrix.packageName }}:build

      - name: Parse package name
        id: parse
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.packageName }}
          pattern: '^@?(?<scope>.*)\/(?<name>.*)$'

      - name: Hash check message
        if: "contains(${{ steps.hash-check-scopes.outputs.scopes }}, ${{ steps.parse.outputs.scope }})"
        run: echo "Checking build hash for ${{ matrix.packageName }}"

      - name: Calculate hash for dist and additional files
        id: calculate-hash
        if: "contains(${{ steps.hash-check-scopes.outputs.scopes }}, ${{ steps.parse.outputs.scope }})"
        uses: seepine/hash-files@v1
        with:
          workdir: ${{ github.workspace }}
          patterns: |
            apps/${{ steps.parse.outputs.name }}/dist/**
            apps/${{ steps.parse.outputs.name }}/scripts/**
            apps/${{ steps.parse.outputs.name }}/nginx.conf

      - name: Check cache for this build
        if: "contains(${{ steps.hash-check-scopes.outputs.scopes }}, ${{ steps.parse.outputs.scope }})"
        id: check-cache
        uses: actions/cache@v3
        with:
          path: /dev/null # No files are restored, we just check existence
          key: build-cache-${{ steps.parse.outputs.name }}-${{ steps.calculate-hash.outputs.hash }}
        continue-on-error: true

      - name: Check if build should be skipped
        id: should-skip
        run: |
          echo "::set-output name=should_skip::${{ steps.check-cache.outputs.cache-hit == 'true' }}"

      - name: Skip build if cache exists
        if: steps.should-skip.outputs.should_skip == 'true'
        run: echo "Cache hit for ${{ matrix.packageName }}. Skipping build."

      - name: Gcloud auth
        if: steps.should-skip.outputs.should_skip != 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Setup gcloud
        if: steps.should-skip.outputs.should_skip != 'true'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          skip_install: true

      - name: Build on Google Cloud
        if: steps.should-skip.outputs.should_skip != 'true'
        run: |
          image=${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}

          cat <<EOF > cloudbuild.yaml
          steps:
            - name: "gcr.io/cloud-builders/docker"
              id: "Build ${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}"
              env:
                - "DOCKER_BUILDKIT=1"
              args:
                - build
                - --target=${{ steps.parse.outputs.name }}
                - --tag=$image:latest
                - --tag=$image:dev-${{ needs.timestamp.outputs.timestamp }}
                - --build-arg=sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}
                - --build-arg=sentry_release=dev-${{ needs.timestamp.outputs.timestamp }}
                - .
          images:
            - $image:latest
            - $image:dev-${{ needs.timestamp.outputs.timestamp }}
          EOF

          gcloud builds submit . \
            --config cloudbuild.yaml \
            --region ${{ vars.GCLOUD_REGISTRY_REGION }} \
            --async

      - name: Set cache for this build hash
        if: steps.should-skip.outputs.should_skip != 'true'
        uses: actions/cache@v3
        with:
          path: /dev/null # No files are stored, we just set the cache
          key: build-cache-${{ steps.parse.outputs.name }}-${{ steps.calculate-hash.outputs.hash }}
