name: Check

on:
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run checks
        run: yarn check:affected
