name: Check

on:
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  check:
    runs-on: [self-hosted, build]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run checks
        run: pnpm check:affected
