name: Deploy dev stack

on:
  push:
    branches: ['main']

env:
  DOCKER_REGISTRY: ${{ vars.GCLOUD_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker

concurrency:
  group: ${{ github.workflow }}

jobs:
  affected:
    name: Get affected apps
    runs-on: ubuntu-latest

    outputs:
      apps: ${{ steps.affected.outputs.apps }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run NX checks
        run: |
          yarn nx affected --target build --parallel 3
          yarn nx affected --target lint --parallel 3
          yarn nx affected --target test --parallel 3
          yarn nx affected --target typecheck --parallel 3

      - name: Output affected apps
        id: affected
        run: |-
          echo "apps=$(yarn nx show projects --type=app --affected --json)" >> $GITHUB_OUTPUT

  publish:
    name: Publish to Google Cloud Registry
    needs: affected
    runs-on: ubuntu-latest

    if: needs.affected.outputs.apps != '[]'

    strategy:
      matrix:
        packageName: ${{ fromJson(needs.affected.outputs.apps) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Authenticate Docker registry
        run: |-
          gcloud auth configure-docker ${{ vars.GCLOUD_REGISTRY_REGION }}-docker.pkg.dev --quiet

      - name: Get package path
        id: packagePath
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.packageName }}
          pattern: '^@?(?<path>.*)$'

      - name: Build image
        run: |-
          docker build . -f ${{ steps.packagePath.outputs.path }}/Dockerfile \
            -t ${{ env.DOCKER_REGISTRY }}/${{ steps.packagePath.outputs.path }}:latest \
            -t ${{ env.DOCKER_REGISTRY }}/${{ steps.packagePath.outputs.path }}:${{ github.sha }}

      - name: Push image
        run: |-
          docker push ${{ env.DOCKER_REGISTRY }}/${{ steps.packagePath.outputs.path }}:latest
          docker push ${{ env.DOCKER_REGISTRY }}/${{ steps.packagePath.outputs.path }}:${{ github.sha }}

  deploy-dev-stack:
    name: Deploy dev stack
    needs: publish
    runs-on: [self-hosted, swarm]

    env:
      NODE_ENV: production
      DATABASE_URL: ${{ vars.DATABASE_URL_DEV }}
      DATABASE_DIRECT_URL: ${{ vars.DATABASE_DIRECT_URL_DEV }}
      PUBLIC_DOMAIN: ${{ vars.PUBLIC_DOMAIN_DEV }}
      PUBLIC_GAMES_APP_URL: ${{ vars.PUBLIC_GAMES_APP_URL_DEV }}
      PUBLIC_GAMES_API_URL: ${{ vars.PUBLIC_GAMES_API_URL_DEV }}
      PUBLIC_GAMES_API_WS_URL: ${{ vars.PUBLIC_GAMES_API_WS_URL_DEV }}
      JWT_SECRET: ${{ vars.JWT_SECRET_DEV }}
      PUBLIC_TELEGRAM_BOT_ID: ${{ vars.PUBLIC_TELEGRAM_BOT_ID_DEV }}
      TELEGRAM_BOT_TOKEN: ${{ vars.TELEGRAM_BOT_TOKEN_DEV }}
      PUBLIC_VK_APP_ID: ${{ vars.PUBLIC_VK_APP_ID_DEV }}
      VK_APP_SECRET: ${{ vars.VK_APP_SECRET_DEV }}
      VK_SERVICE_TOKEN: ${{ vars.VK_SERVICE_TOKEN_DEV }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Authenticate Docker registry
        run: |-
          gcloud auth configure-docker ${{ vars.GCLOUD_REGISTRY_REGION }}-docker.pkg.dev --quiet

      - name: Deploy dev stack
        run: |-
          docker stack deploy -c stacks/dev.docker-compose.yml dev --with-registry-auth --prune
