name: Publish to Google Cloud Registry

on:
  push:
    branches: ['main']

env:
  DOCKER_REGISTRY: ${{ vars.GCLOUD_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker

concurrency:
  group: ${{ github.workflow }}

jobs:
  affected:
    name: Get affected apps
    runs-on: ubuntu-latest

    outputs:
      apps: ${{ steps.affected.outputs.apps }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run checks
        run: pnpm check:affected

      - name: Output affected apps
        id: affected
        run: |-
          echo "apps=$(pnpm nx show projects --type=app --affected --json)" >> $GITHUB_OUTPUT

  publish:
    name: Publish to Google Cloud Registry
    needs: affected
    runs-on: ubuntu-latest

    if: needs.affected.outputs.apps != '[]'

    strategy:
      matrix:
        packageName: ${{ fromJson(needs.affected.outputs.apps) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Authenticate Docker registry
        run: |-
          gcloud auth configure-docker ${{ vars.GCLOUD_REGISTRY_REGION }}-docker.pkg.dev --quiet

      - name: Parse package name
        id: parse
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.packageName }}
          pattern: '^@?(?<folder>.*)\/(?<name>.*)$'

      - name: Build image
        run: |-
          docker build . --target ${{ steps.parse.outputs.name }} \
            --tag ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.folder }}/${{ steps.parse.outputs.name }}:latest \
            --tag ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.folder }}/${{ steps.parse.outputs.name }}:dev-${{ github.sha }}

      - name: Push image
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.folder }}/${{ steps.parse.outputs.name }}:latest
