name: Publish apps

on:
  push:
    branches: ['main']

env:
  GCLOUD_TAG_BASEPATH: ${{ vars.GCLOUD_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker

concurrency:
  group: ${{ github.workflow }}

jobs:
  run-changesets:
    name: Run Changesets
    runs-on: ubuntu-latest

    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create Release Pull Request or Tags
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'Version Apps'
          commit: 'chore(changesets): version apps'
          publish: yarn changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    needs: run-changesets
    runs-on: ubuntu-latest
    if: needs.run-changesets.outputs.published == 'true'

    strategy:
      matrix:
        package: ${{ fromJson(needs.run-changesets.outputs.publishedPackages) }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build app
        run: yarn nx run ${{ matrix.package.name }}:build

      - name: Get package path
        id: packagePath
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.package.name }}
          pattern: '^@?(?<normalized>.*)$'

      - name: Archive Dockerfile deps without symlinked node_modules
        run: |-
          tar -hcf workspace.tar node_modules
          tar -rf workspace.tar -C ${{ steps.packagePath.outputs.normalized }} dist
          tar -rf workspace.tar -C ${{ steps.packagePath.outputs.normalized }} Dockerfile
          gzip workspace.tar

      - name: Build image using Google Cloud Build
        run: |-
          gcloud builds submit "workspace.tar.gz" \
            --tag ${{ env.GCLOUD_TAG_BASEPATH }}/${{ steps.packagePath.outputs.normalized }}:${{ matrix.package.version }} \
            --timeout 1h
