name: Publish development images to GCR

on:
  push:
    branches: ['main', 'draft/build-process']

env:
  DOCKER_REGISTRY: europe-north1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker

concurrency:
  group: ${{ github.workflow }}

jobs:
  timestamp:
    name: Get current unix timestamp
    runs-on: arc-runner-set

    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}

    steps:
      - name: Get current unix timestamp
        id: timestamp
        uses: release-kit/unix-timestamp@v1

  affected:
    name: Get affected apps
    runs-on: arc-runner-set

    outputs:
      apps: ${{ steps.affected.outputs.apps }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        id: pnpm
        with:
          version: 9.12.2
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Run checks for affected packages
        run: pnpm check:affected

      - name: Build all apps
        run: pnpm build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"] 

      - name: Prebuild
        run: docker build . --target prebuild --platform linux/amd64

      - name: Output affected apps
        id: affected
        run: echo "apps=$(pnpm nx show projects --type=app --affected --json)" >> $GITHUB_OUTPUT

  publish:
    name: Publish
    needs: [affected, timestamp]
    runs-on: arc-runner-set

    if: needs.affected.outputs.apps != '[]'

    strategy:
      fail-fast: false
      matrix:
        packageName: ${{ fromJson(needs.affected.outputs.apps) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        id: pnpm
        with:
          version: 9.12.2
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"] 

      - name: Authenticate Docker registry
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Parse package name
        id: parse
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.packageName }}
          pattern: '^@?(?<scope>.*)\/(?<name>.*)$'

      - name: Build image
        run: |-
          docker build . --target ${{ steps.parse.outputs.name }} \
            --build-arg sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }} \
            --build-arg sentry_release=dev-${{ needs.timestamp.outputs.timestamp }} \
            --tag ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:latest \
            --tag ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:dev-${{ needs.timestamp.outputs.timestamp }} \
            --platform linux/amd64

      - name: Push image
        run: |-
          docker push ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:latest
          docker push ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:dev-${{ needs.timestamp.outputs.timestamp }}
