name: Publish apps

on:
  push:
    branches: ['main']

env:
  GCLOUD_TAG_BASEPATH: ${{ vars.GCLOUD_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker

jobs:
  run-changesets:
    name: Run Changesets
    runs-on: ubuntu-latest

    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create Release Pull Request or Tags
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prepublish:
    name: Prepublish
    needs: run-changesets
    runs-on: ubuntu-latest

    if: needs.run-changesets.outputs.published == 'true'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build affected packages
        run: yarn nx affected --target build --parallel 3

      - name: Archive workspace without symlinked node_modules
        run: tar -cf workspace.tgz --exclude=workspace.tgz .

      - uses: actions/upload-artifact@v3
        with:
          name: workspace-${{ github.sha }}
          path: workspace.tgz
          retention-days: 1

  publish:
    name: Publish
    needs: [run-changesets, prepublish]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.run-changesets.outputs.publishedPackages) }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - uses: actions/download-artifact@v3
        with:
          name: workspace-${{ github.sha }}

      - name: Normalize package name for docker tag
        id: imageName
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.package.name }}
          pattern: '^@?(?<normalized>.*)$'

      - name: Build image using Google Cloud Build
        run: |-
          gcloud builds submit "workspace.tgz" \
            --tag ${{ env.GCLOUD_TAG_BASEPATH }}/${{ steps.imageName.outputs.normalized }}:${{ matrix.package.version }} \
            --timeout 1h
