name: Publish development images to GCR

on:
  push:
    branches: ['main', 'draft/build-process']

env:
  DOCKER_REGISTRY: europe-north1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker
  WORKSPACE_DIRECTORY: /workspace/${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  copy-repository:
    name: Copy repository
    runs-on: arc-runner-set

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy repository
        run: |-
          echo $GITHUB_PATH
          echo $PATH
          mkdir -p ${{ env.WORKSPACE_DIRECTORY }}
          cp -r . ${{ env.WORKSPACE_DIRECTORY }}
          chown -R :runner ${{ env.WORKSPACE_DIRECTORY }}
          chmod -R 755 ${{ env.WORKSPACE_DIRECTORY }}

  affected:
    name: Get affected apps
    needs: copy-repository
    runs-on: arc-runner-set
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE_DIRECTORY }}

    outputs:
      apps: ${{ steps.affected.outputs.apps }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: pnpm/action-setup@v4
        id: pnpm
        with:
          version: 9.12.2
          dest: ${{ env.WORKSPACE_DIRECTORY }}/.pnpm
          run_install: false

      - name: Link pnpm to /bin
        run: |-
          ln -s ${{ steps.pnpm.outputs.bin_dest }}/pnpm /bin/pnpm
          ln -s ${{ steps.pnpm.outputs.bin_dest }}/pnpx /bin/pnpx
          ln -s ${{ steps.pnpm.outputs.bin_dest }}/pnpm /home/runner/bin/pnpm
          ln -s ${{ steps.pnpm.outputs.bin_dest }}/pnpx /home/runner/bin/pnpx
      
      - name: Check
        run: |-
          echo $PATH
          ls /bin/pnpm
          ls /bin/pnpx
          ls /home/runner/bin/pnpm
          ls /home/runner/bin/pnpx

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          working-directory: ${{ env.WORKSPACE_DIRECTORY }}

      - name: Run checks for affected packages
        run: pnpm check:affected

      - name: Build all apps
        run: pnpm build

      - name: Prebuild docker stage
        run: docker build . --target build --platform linux/amd64

      - name: Output affected apps
        id: affected
        run: echo "apps=$(pnpm nx show projects --type=app --affected --json)" >> $GITHUB_OUTPUT

      - name: Remove all artifacts
        run: |-
          find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
          find . -name 'dist' -type d -prune -exec rm -rf '{}' +

  publish:
    name: Publish
    needs: [affected, copy-repository]
    runs-on: arc-runner-set
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE_DIRECTORY }}

    if: needs.affected.outputs.apps != '[]'

    strategy:
      fail-fast: false
      matrix:
        packageName: ${{ fromJson(needs.affected.outputs.apps) }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set gcloud project
        run: gcloud config set project ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Write gcloud service key to file
        run: printf '%s' '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}' > /tmp/gcloud-service-key.json

      - name: Auth gcloud service account
        run: gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json

      - name: Authenticate Docker registry
        run: |-
          gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Parse package name
        id: parse
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.packageName }}
          pattern: '^@?(?<scope>.*)\/(?<name>.*)$'

      - name: Get current unix timestamp
        id: timestamp
        uses: release-kit/unix-timestamp@v1

      - name: Build image
        run: |-
          docker build . --target ${{ steps.parse.outputs.name }} \
            --build-arg sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }} \
            --build-arg sentry_release=dev-${{ steps.timestamp.outputs.timestamp }} \
            --tag ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:latest \
            --tag ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:dev-${{ steps.timestamp.outputs.timestamp }} \
            --platform linux/amd64

      - name: Push image
        run: |-
          docker push ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:latest
          docker push ${{ env.DOCKER_REGISTRY }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:dev-${{ steps.timestamp.outputs.timestamp }}

  cleanup:
    name: Cleanup
    needs: [copy-repository, publish]
    runs-on: arc-runner-set

    steps:
      - name: Clean docker images
        run: docker image prune -a --force --filter "until=6h"
