name: Publish to Google Cloud Registry

on:
  push:
    branches: ['main']
    paths-ignore:
      - '.github/workflows/test.yml'

env:
  DOCKER_REGISTRY: registry.sigmacloud.app
  DOCKER_PROJECT: registry.sigmacloud.app/sigma
  WORKSPACE_DIRECTORY: /tmp/workspace/${{ github.run_id }}
  WORKSPACE_RUN_DIRECTORY: /tmp/workspace/${{ github.run_id }}/${{ github.run_attempt }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  copy-repository:
    name: Copy repository
    runs-on: [self-hosted, build, ARM64]
    defaults:
      run:
        shell: zsh {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy repository
        run: |-
          mkdir -p ${{ env.WORKSPACE_RUN_DIRECTORY }}
          cp -r . ${{ env.WORKSPACE_RUN_DIRECTORY }}

  affected:
    name: Get affected apps
    needs: copy-repository
    runs-on: [self-hosted, build, ARM64]
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE_RUN_DIRECTORY }}
        shell: zsh {0}

    outputs:
      apps: ${{ steps.affected.outputs.apps }}

    steps:
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          working-directory: ${{ env.WORKSPACE_RUN_DIRECTORY }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run checks and build
        run: pnpm check:affected

      - name: Prebuild docker stage
        run: docker build . --target build --platform linux/amd64

      - name: Output affected apps
        id: affected
        run: echo "apps=$(pnpm nx show projects --type=app --affected --json)" >> $GITHUB_OUTPUT

  publish:
    name: Publish
    needs: [affected, copy-repository]
    runs-on: [self-hosted, build, ARM64]
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE_RUN_DIRECTORY }}
        shell: zsh {0}

    if: needs.affected.outputs.apps != '[]'

    strategy:
      fail-fast: false
      matrix:
        packageName: ${{ fromJson(needs.affected.outputs.apps) }}

    steps:      
      - name: Authenticate Docker registry
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ env.DOCKER_REGISTRY }} --username ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Parse package name
        id: parse
        uses: release-kit/regex@v1
        with:
          string: ${{ matrix.packageName }}
          pattern: '^@?(?<scope>.*)\/(?<name>.*)$'

      - name: Get current unix timestamp
        id: timestamp
        uses: release-kit/unix-timestamp@v1

      - name: Build image
        run: |-
          docker build . --target ${{ steps.parse.outputs.name }} \
            --build-arg sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }} \
            --build-arg sentry_release=dev-${{ steps.timestamp.outputs.timestamp }} \
            --tag ${{ env.DOCKER_PROJECT }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:latest \
            --tag ${{ env.DOCKER_PROJECT }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:dev-${{ steps.timestamp.outputs.timestamp }} \
            --platform linux/amd64

      - name: Push image
        run: |-
          docker push ${{ env.DOCKER_PROJECT }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:latest
          docker push ${{ env.DOCKER_PROJECT }}/${{ steps.parse.outputs.scope }}/${{ steps.parse.outputs.name }}:dev-${{ steps.timestamp.outputs.timestamp }}

  cleanup:
    name: Cleanup
    needs: [copy-repository, publish]
    runs-on: [self-hosted, build, ARM64]
    defaults:
      run:
        shell: zsh {0}

    steps:
      - name: Clean docker images
        run: docker image prune -a --force --filter "until=6h"
      
      - name: Clean temporary files
        run: rm -rf ${{ env.WORKSPACE_DIRECTORY }}
