name: Test

on:
  push:
    branches: ['main']

env:
  DOCKER_REGISTRY: harbor.sigmacloud.app
  DOCKER_PROJECT: harbor.sigmacloud.app/sigma
  WORKSPACE_DIRECTORY: /tmp/workspace/${{ github.run_id }}
  WORKSPACE_RUN_DIRECTORY: /tmp/workspace/${{ github.run_id }}/${{ github.run_attempt }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  copy-repository:
    name: Copy repository
    runs-on: [self-hosted, build, ARM64]
    defaults:
      run:
        shell: zsh {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy repository
        run: |-
          mkdir -p ${{ env.WORKSPACE_RUN_DIRECTORY }}
          cp -r . ${{ env.WORKSPACE_RUN_DIRECTORY }}

  publish:
    name: Publish
    needs: copy-repository
    runs-on: [self-hosted, build, ARM64]
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE_RUN_DIRECTORY }}
        shell: zsh {0}

    steps:
      - name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

  cleanup:
    name: Cleanup
    needs: [copy-repository, publish]
    runs-on: [self-hosted, build, ARM64]
    defaults:
      run:
        shell: zsh {0}

    steps:
      - name: Clean docker images
        run: docker image prune -a --force --filter "until=6h"
      
      - name: Clean temporary files
        run: rm -rf ${{ env.WORKSPACE_DIRECTORY }}
